### ISSUE TITLE
line continuation pattern specified twice

### ISSUE THREAD

**Issue by manpreetszr** [vim-jp/syntax-vim-ex#22]
The following error has been happening constantly for a long while now:

```
Error detected while processing /home/foo/.config/nvim/bundles/syntax-vim-ex/syntax/vim.vim:
line  865:
E403: syntax sync: line continuations pattern specified twice
```

**Comment by h-east** [comment]
I can't reproduce it.
Would you please write the reproduction procedure step by step?

**Comment by manpreetszr** [comment]
Never mind. I can reproduce it even with vim81's bundled vim.vim syntax file with something in my config. Happens to me whenever I open any `*.rst` file. I'll reopen if needed.
