### ISSUE TITLE
Include with Vim

### ISSUE THREAD

**Issue by chrisbra** [vim-jp/syntax-vim-ex#28]
Hi, 
I'd like to re-use the vim-script generator and include it with Vim https://github.com/vim/vim/issues/13939. However, I see quite a few differences when running the Vim script syntax tests. I see the following failures:

It highlights (which upstream vim does not):
- `:Next`
- `:Print`
- `:X`

It doesn't highlight (which upstream vim does):

- `2match`
- `3match`
- `abbreviate`
- `augroup`
- `behave`
- `cabbrev`
- `cnoreabbrev`
- `cunmap`
- `echohl`
- `execute`
- `filetype`
- `global/.../` (the `/` delimiters), same for `:vglobal`
- `iabbrev`
- `inoreabbrev`
- `iunmap`
- `lunmap`
- `noreabbrev`
- `normal`
- `nunmap`
- `ounmap`
- `sunmap`
- `tunmap`
- `unmap`
- `vunmap`
- `xunmap`
- String interpolation `$"...."` (the `$`)
- Hex, Unicode and Octal, Key Codes (e.g. `\XF - \u02a4`) it highlights jus the `\X` while Vim highlights the whole word
- `<NL>`, `<NewLine>`, `<Enter>`, `<CSI>`, `<xCSI>`, `<PasteStart>`, `<PasteEnd>`, `<kInsert>`, `<zHome>`, `<zEnd>`
- `<NetMouse>`, `<DecMouse>`, `<JsbMouse>`, `<PtermMouse>`, `<UrxvtMouse>`, `<SgrMouse>`, `<SgrMouseRelease>`, `<LeftReleaseNM>`, `<MouseMove>`, `<ScrollWheelUp>`, `<ScrollWheelDown>`, `<ScrollWheelRight>`, `<ScrollWheelLeft>`, `<MouseDown>`, `<MouseUp>`, `<X1Mouse>`, `<X1Drag>`, `<X1Release>`, `<X2Mouse>`, `<X2Drag>`, `<X2Release>`, `<Drop>`
- `<SNR>`, `<CursorHold>`, `<ScriptCmd>`, `<FocusGained>`, `<FocusLost>`, `<stack>`, `<sflnum>`
- `<script>` is highlighted differently than Vim
- Line continuation: `"\ ...."`
- `conceal`
- `cchar=..`
- `contained`
- `containedin`
- `nextgroup`
- `transparent`
- `skipwhite`
- `skipempty`
- `skipnl`
- `contains`
- `oneline`
- `extend`
- `concealends`
- `excludenl`
- `keepend`
- `add/remove`
- `%=`, `/=`, `*=`
- register names `@f = `
- option names `let &g:foo = `
- List unpack: `let [foo, bar] .= expr`
- `unlet foo bar`
- `const foo = expr`

You can run the Vim Syntax scripts and see the results like this: 
```
cd ~/code/vim/runtime/syntax/
make
cat testdir/messages
for i in testdir/failed/*.dump; do vim --clean -c "call term_dumpdiff(\"testdir/failed/${i##*/}\", \"testdir/dumps/${i##*/}\")"; done
```

Do you think, this can be fixed? What do you think?

**Comment by h-east** [comment]
Hi,
I also ran Vim script syntax tests in my environment and confirmed that there was a difference as pointed out.
I'll work on this fix. Wait a few days.

**Comment by h-east** [comment]
The Vim script syntax tests is clear.
