### ISSUE TITLE
事後報告: depth を増加

### ISSUE THREAD

**Issue by koron** [vim-jp/syntax-vim-ex#4]
0a2ca07c0e4b85c2bcfa197af1cca85bf05bd433 で修正済みの内容です。

Vim を取り出す `submodule update` が `--depth 1` だったため、
Vimの更新が進んでいると意図したrevisionが取り出せずに、travis-ciが失敗していました。
これを `--depth 50` に変更し、少しくらい古くなっても取り出せるようにしました。

あと vim を 7.4.1362 にキャッチアップしておきました。

**Comment by h-east** [comment]
:+1: 
`README.md`の記述(--depth 1)も修正が必要です？

**Comment by koron** [comment]
@h-east #5 で対応しました。

**Comment by h-east** [comment]
ありがとうございます。PR Mergeしました。
