### ISSUE TITLE
前回からの差分を見れるようにしたい

### ISSUE THREAD

**Issue by h-east** [vim-jp/syntax-vim-ex#6]
syntax/vim.vimの前回からの差分を見れるようにしたい。
`vim.vim`をaddして良いですか？
他に良いソリューションがあれば提案下さい。

**Comment by koron** [comment]
手元で? vim.vim を add するのは、あまり好ましくないですが…。

リモートで良ければ gh-pages で比較とか。
https://github.com/vim-jp/gen_syn_vim/commit/1fa7a8dff7d37b5ba19a61bad2aa230cc4e47964

**Comment by tyru** [comment]
add するならできれば `.vim/bundle` の構成にしてもらえると嬉しいです。
(`/syntax/vim.vim` のような構成)

**Comment by h-east** [comment]
@koron あっ、そうかTravisCIがアップしているからそこを見れば良いんだった。:+1:
あと、`git diff --word-diff` 的な表示で差分見れましたっけ？
(1行768文字のどこが変わったかパッと分かりたい... ってローカルにチェックアウトしてgit使えばいいか)

@tyru gh-pagesはそういう構成になっていますね。
https://github.com/vim-jp/gen_syn_vim/tree/gh-pages/syntax/vim.vim

**Comment by h-east** [comment]
閉じます。

**Comment by tyru** [comment]
@h-east なるほど。ありがとうございます。
