### ISSUE TITLE
一般ユーザーがinstall/updateしやすくなるように改善する

### ISSUE THREAD

**Issue by h-east** [vim-jp/syntax-vim-ex#7]
こんな感じでどうでしょうか？
### 導入手順

``` sh
$ cd ~/.vim
$ mkdir -p pack/my/opt
$ cd pack/my/opt
$ git clone -b gh-pages --depth 1 https://github.com/vim-jp/gen_syn_vim.git
```

.vimrc に以下の1行を追加。

``` vim
packadd! gen_syn_vim
```
### 更新手順

``` sh
$ cd ~/.vim/pack/my/opt/gen_syn_vim
$ git pull
```
##### cd & git:
- Windowsの場合は`~/.vim`を`$HOME/vimfiles`に読み替えて下さい。  
  あと`mkdir`の`-p`オプションは不要です。
- ディレクトリ名`my`は好きな名前に変更可能です。
- この例のように`~/.vim`ディレクトリ下にパッケージを構成する場合は`packpath`の設定は不要です。
##### .vimrc:
- もし、`packloadall`を呼んでいる場合はそれよりも前で呼んで下さい。  
  `packloadall`相当の処理は`.vimrc`読み込み後に自動的におこなわれますので必ずしも呼び出す必要はありません。

**Comment by tyru** [comment]
> git clone git@github.com:vim-jp/gen_syn_vim.git

ユーザ向けなので ssh ではなく https の URL の方が良いんじゃないでしょうか？

**Comment by h-east** [comment]
@tyru Thanks! 修正しました。

**Comment by k-takata** [comment]
> $ git checkout -b gh-pages origin/gh-pages

単純に、`$ git checkout gh-pages` でよいと思います。（もしかして比較的新しいバージョンのみ？）
あるいは、`$ git checkout -t origin/gh-pages`

**Comment by h-east** [comment]
@k-takata Thanks! `$ git checkout gh-pages`に修正しました。

**Comment by koron** [comment]
gen_syn_vim って名前、使う方からしたら、パッケージとしてはわかりにくくありませんかね。

という余談はさておき、clone を `-b` 付きでやると2手減らせます。
あとは `--depth` を付けると通信量が減って嬉しいかも。
とりあえず下の例では1でにしましたが…

```
git clone -b gh-pages --depth 1 https://github.com/vim-jp/gen_syn_vim.git
```

**Comment by h-east** [comment]
@koron ありがとthanks! `git clone`の行を修正しました。

> gen_syn_vim って名前、使う方からしたら、パッケージとしてはわかりにくくありませんかね。

うーん、、パッケージ名何が良いんだろう。。募集中❤
precise_syntax_vim ?

**Comment by tyru** [comment]
autogen-syntax-vim とかどうでしょう。

**Comment by koron** [comment]
使う方としては syntax-vim とか syntax-vim-revised みたいな感じじゃないですかね。

**Comment by DeaR** [comment]
パッケージ名だけでなくDescriptionやDefaultBranchもGenerator(master)ではなくGenerated syntax(gh-pages)の方が易しい気がします

実際私も、手元でビルドするのか、とちょっと身構えました

**Comment by h-east** [comment]
@DeaR ご意見thanks!

masterブランチはユーザーclone用、generatorブランチは開発用という構成でどうでしょうか。

```
(Package name)
  master branch
  |-- _config.yml
  |-- README.md
  `-- syntax/
      `-- vim.vim

  generator branch
  |-- Makefile
  |-- gen_syntax_vim.vim
  |-- tools/
  |   |-- ci@gen_syn_vim.vim-jp.org.enc
  |   |-- deploy-master.sh
  |   `-- install_sshkey_github.sh
  |-- update_date.vim
  |-- vim/   (submodule)
  `-- vim.vim.base

  gh-pages branch
  ...
```

**Comment by koron** [comment]
@h-east レポジトリ名変更やブランチ名変更は travis との関係でデリケートな部分があるので、特に意見がなければ私が引き受けますので、それらの名前が決まったら言ってください。

**Comment by h-east** [comment]
syntax-vim-ex で良い？

パッケージ名を考えててふと思ったんだけど、`packadd`ってパッケージ名(ディレクトリ名)だけの指定だから被りやすいね。あと、自己顕示欲が満たされにくい(ふははは)

**Comment by h-east** [comment]
パッケージ名は`syntax-vim-ex`にします。
ブランチ名はmasterとgeneratorで。gh-pagesはいらないかも。

@koron お手数ですが変更をお願い致します。

**Comment by koron** [comment]
承知しました。今夜から、明日にかけて作業します。
作業の前後でアナウンスしますので、その間はレポジトリを触らないでいただけると、助かります。

**Comment by h-east** [comment]
All＞
README.md書いてみました。内容&Englishの添削お願いします。

# syntax-vim-ex

An excellent Vim syntax highlighting file for Vim.  

## Difference between [original](https://github.com/vim/vim/blob/master/runtime/syntax/vim.vim)
- The syntax-vim-ex has been generated by parse the C source code of Vim.  
  So keyword extraction is accurate.
- Omitted keyword extraction algorithm of Ex command is perfect because it is same and the C source code of Vim.
- It will immediately follow the Vim updates.
- Generator source code is all open sourced.  (See generator branch)

## Install

``` sh
$ cd ~/.vim
$ mkdir -p pack/my/opt
$ cd pack/my/opt
$ git clone --depth 1 https://github.com/vim-jp/syntax-vim-ex.git
```

Add following line to your `.vimrc`.

``` vim
packadd! syntax-vim-ex
```

Remarks:
- In the case of Windows should read the `~/.vim` to `$HOME/vimfiles`.  
  And mkdir `-p` option is not required.
- Directory name `my` can be changed to any name.
- If you want to configure the package under `~/.vim` directory as in this example the setting of `packpath` is not required.
- If you are calling `packloadall`, `packadd` should call in before it.

## Update

``` sh
$ cd ~/.vim/pack/my/opt/syntax-vim-ex
$ git pull
```

## Licence

Follow the [Vim license](https://github.com/vim/vim/blob/master/README.md#copying).

## Author

[Hirohito Higashi](https://github.com/h-east) and [vim-jp](http://vim-jp.org/)
Charles E. Campbell (Original `syntax/vim.vim` author.  We are based on this file)

**Comment by DeaR** [comment]
s/`packadd! gen_syn_vim`/`packadd! syntax-vim-ex`/

**Comment by h-east** [comment]
@DeaR ありがとうございます。修正しました。

**Comment by koron** [comment]
作業開始します。

**Comment by koron** [comment]
作業完了しました。

README.md は多少修正した英語版だけをcommitしました。
issue冒頭の日本語版とはズレがありましたので、必要ならば翻訳してください。

新 master の一発目の commit では、
syntax/vim.vimをCRLFで入れるというポカをやらかしましたが、
勘弁してください :bow:

以上です。

**Comment by h-east** [comment]
@koron 変更作業ありがとうございました。:+1:
Issueのタイトル変更しました。

**Comment by h-east** [comment]
@koron  generatorブランチのREADME.mdの内容をブランチ名変更にあわせて修正しました。
